name: pazimo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter_svg: 2.0.10+1
  google_fonts: 6.2.1
  flutter_otp_text_field: 1.1.3+2
  cached_network_image: ^3.3.1
  flutter_launcher_icons: 0.13.1
  lottie: 3.1.0
  flutter_native_splash: 2.4.0
  dio: 5.4.3+1
  get_storage: 2.1.1
  flutter_screenutil: 5.9.0
  flutter_rating_bar: 4.0.1
  collection: 1.18.0
  intl: 0.19.0
  google_sign_in: 6.2.1
  shimmer: 3.0.0
  carousel_slider: 4.2.1
  chips_choice: 3.0.1
  intl_phone_field: 3.2.0
  image_picker: 1.1.2
  flutter_easyloading: 3.0.5
  smooth_page_indicator: 1.1.0
  syncfusion_flutter_charts: 26.1.39
  dotted_border: ^2.1.0
  sign_in_with_apple: 6.1.1
  badges: 3.1.2
  flutter: 
    sdk: flutter

flutter_launcher_icons: 
  image_path: assets/images/pazimo_logo.png
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter
  android: true
  ios: true

flutter: 
  assets: 
    - assets/svg/
    - assets/images/
    - assets/lottie/
  uses-material-design: true

flutter_native_splash: 
  color: '#FFFFFF'
  image: assets/images/pazimo_logo.png

